version: '3.8'
services:
  app:
    build:
      context: /gimnasio-backend
      dockerfile: Dockerfile
    container_name: gimnasio-backend
    ports:
      - "8080:8080" # Mapea el puerto de la aplicación backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gimnasiodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db # Asegura que la base de datos esté disponible antes de iniciar la aplicación

  db:
    image: mysql:8.0 # Imagen de MySQL 8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gimnasiodb
    ports:
      - "3306:3306" # Mapea el puerto de la base de datos para acceder desde tu máquina
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos

  frontend:
    build:
      context: /gimnasio-frontend
      dockerfile: Dockerfile
    container_name: gimnasio-frontend
    ports:
      - "4200:80" # El frontend estará accesible en el puerto 4200
    depends_on:
      - app

volumes:
  db_data:

